"""changed DateTime to Date

Revision ID: 099981b6db21
Revises: ee05def31475
Create Date: 2024-07-18 01:43:02.607817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '099981b6db21'
down_revision = 'ee05def31475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.alter_column('loan_date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('returned_date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.alter_column('returned_date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('loan_date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    # ### end Alembic commands ###
